// Code generated by redis-orm. DO NOT EDIT !
package model

import (
	"github.com/ezbuy/redis-orm/example/rpc/blog"
)

// ConvertBlogModelToblogRPC1PB converts model to defined pb columns.
func ConvertBlogModelToblogRPC1PB(md *Blog) *blog.RPC1 {
	pb := new(blog.RPC1)
	pb.UserID = int64(md.UserId)
	pb.Title = string(md.Title)
	return pb
}

// ConvertblogRPC1PBToBlogModel converts defined pb columns to model.
func ConvertblogRPC1PBToBlogModel(pb *blog.RPC1) *Blog {
	md := new(Blog)
	md.UserId = int32(pb.UserID)
	md.Title = string(pb.Title)
	return md
}

// ConvertBlogModelToblogRPC2PB converts model to defined pb columns.
func ConvertBlogModelToblogRPC2PB(md *Blog) *blog.RPC2 {
	pb := new(blog.RPC2)
	pb.UserID = int64(md.UserId)
	pb.Title = string(md.Title)
	return pb
}

// ConvertblogRPC2PBToBlogModel converts defined pb columns to model.
func ConvertblogRPC2PBToBlogModel(pb *blog.RPC2) *Blog {
	md := new(Blog)
	md.UserId = int32(pb.UserID)
	md.Title = string(pb.Title)
	return md
}
