
CREATE TABLE `testCRUD` (
	`office_id` INT(11) NOT NULL AUTO_INCREMENT,
	`office_area` VARCHAR(100) NOT NULL DEFAULT '',
	`office_name` VARCHAR(100) NOT NULL DEFAULT '',
	`search_origin_code` VARCHAR(100) NOT NULL DEFAULT '',
	`processing_origin_code` VARCHAR(100) NOT NULL DEFAULT '',
	`create_by` VARCHAR(100) NOT NULL DEFAULT '',
	`update_by` VARCHAR(100) NOT NULL DEFAULT '',
	`create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`office_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'testCRUD';

