
DROP TABLE IF EXISTS `blogs`;
CREATE TABLE `blogs` (
	`id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`title` VARCHAR(100) NOT NULL DEFAULT '',
	`content` VARCHAR(100) NOT NULL DEFAULT '',
	`status` INT(11) NOT NULL DEFAULT '0',
	`readed` INT(11) NOT NULL DEFAULT '0',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE INDEX `user_id_of_blog_i_d_x` ON `blogs`(`user_id`);



