name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test
    strategy:
      matrix:
        go: [1.13,1.14,1.15,1.16]

    runs-on: ubuntu-latest

    container:
        image: golang:${{ matrix.go }}-stretch

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ezbuy
          MYSQL_PASSWORD: ezbuyisthebest
          MYSQL_ROOT_PASSWORD: ezbuyisthebest
          MYSQL_DATABASE: testing
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: bitnami/redis
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD=123456
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Generate TPL
      run: |
        GO111MODULE=off go get -u github.com/jteeuwen/go-bindata/...
        make buildTpl

    - name: Test Builder
      run: |
        go install
        redis-orm code -i ./example/yaml/ -o ./example/model/
        redis-orm sql -i ./example/yaml/ -o ./example/script/
        go test -v ./orm
        go test -v ./orm/sqlbuilder

    - name: Test Model
      run: |
        go test -v ./example/model/
      env:
        MYSQL_HOST: mysql
        MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        REDIS_AUTH: 123456
