name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test
    strategy:
      matrix:
        go: [1.12,1.13,1.14]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Generate TPL
      run: |
        GO111MODULE=off go get -u github.com/jteeuwen/go-bindata/...
        make buildTpl

    - name: Test
      run: |
        go install
        redis-orm code -i ./example/yaml/ -o ./example/model/
        go test -v ./orm/sqlbuilder
